### Przykład 1: Standardowy transport
POST http://localhost:8000/api/v1/parse
Content-Type: application/json
X-API-Key: S74y3DX7KCy84uw-Oq-6MYFyY2lANnir1PEUf_wNaBM

{
    "prompt": "Potrzebuję transportu z Warszawy do Sierpca. Towar: 10 palet, waga 500kg, wymiary 120x80x150cm. Termin: jutro. dowóz następnego dnia"
}

### LDM
POST http://localhost:8000/api/v1/parse
Content-Type: application/json
X-API-Key: 2lx5x5BXzmRGHT-JAzGna7mOPDhSuoQ1D8uxocDLKTw

{
    "prompt": "chcę przewieźć 3 palety 100x80 cm o wysokości 2 metry odbiór 42-445 Szczekociny dostawa 34-442 Łapsze Niżne"
}

### LDM 2
POST http://localhost:8000/api/v1/parse
Content-Type: application/json
X-API-Key: twój_klucz_api

{
    "prompt":  "chcę przewieźć 4 palety 100x80 cm o wysokości 2 metry odbiór 42-445 Szczekociny dostawa 34-442 Łapsze Niżne"
}

### Przykład 4: Transport z obsługą załadunku
POST http://localhost:8000/api/v1/parse
Content-Type: application/json
X-API-Key: twój_klucz_api

{
    "prompt": "chcę przewieźć 4 palety 100x80 cm o wysokości 2 metry odbiór 22-405 Zamość dostawa 86-302 Grudziądz odbiór za 3 dni dowóz następnego dnia"
}
